import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.EJUICE_PLAYWRIGHT||'playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({acceptDownloads:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.EJUICE_URL||'http://127.0.0.1:8080');
await page.getByRole('heading',{name:'Blandinger',exact:true}).waitFor();
await page.getByRole('link',{name:'Ingredienser',exact:true}).click();
await page.getByRole('button',{name:'+ Ny ingrediens'}).click();
await page.locator('[data-field="name"]').fill('Neutral test');
await page.locator('[data-field="category"]').selectOption('base');
await page.locator('[data-field="pg"]').fill('50');await page.locator('[data-field="vg"]').fill('50');
await page.getByRole('button',{name:'Brug beregnet standardvægtfylde'}).click();
await page.getByRole('button',{name:'+ Ny ingrediens'}).click();
await page.locator('[data-field="name"]').fill('Aroma test');
await page.locator('[data-field="purchasedFrom"]').fill('VapeShop');await page.locator('[data-field="purchaseUrl"]').fill('https://example.com/aroma');await page.locator('[data-field="purchasePrice"]').fill('79.95');await page.locator('[data-field="purchaseAmount"]').fill('30');assert.equal((await page.locator('.purchase-result').innerText()),'2,67 kr. pr. ml');
await page.getByRole('link',{name:'Blandinger',exact:true}).click();
await page.getByRole('button',{name:'+ Ny blanding'}).click();
await page.locator('[data-field="recipeName"]').fill('Browser test');
await page.locator('[data-field="target"]').fill('0');
await page.getByRole('button',{name:'+ Tilføj ingrediens'}).click();
await page.locator('[data-row="ingredientId"]').selectOption({label:'Aroma test'});
await page.locator('[data-row="amount"]').fill('10');
await page.reload();await page.getByRole('button',{name:/Browser test/}).click();
assert.equal(await page.locator('[data-row="amount"]').inputValue(),'10');
await page.getByRole('button',{name:'↶ Fortryd'}).click();assert.equal(await page.locator('[data-row="amount"]').inputValue(),'0');
await page.getByRole('button',{name:'↷ Gentag'}).click();
await page.getByRole('button',{name:'Gem afprøvning',exact:true}).click();await page.locator('dialog textarea').fill('God start');await page.getByRole('button',{name:'Bekræft'}).click();
await page.getByRole('button',{name:'Gem som ny version',exact:true}).click();await page.locator('dialog textarea').fill('Godkendt');await page.getByRole('button',{name:'Bekræft'}).click();
await page.getByRole('button',{name:'Lav batch',exact:true}).click();await page.getByRole('button',{name:'10 ml',exact:true}).click();await page.locator('#batch-size').fill('12,5');assert.ok((await page.locator('#batch-result').innerText()).includes('12,50'));
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/private/tmp/ejuice-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.getByRole('link',{name:'Mere',exact:true}).click();const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Gem bibliotek på enhed'}).click();const download=await downloaded;await download.saveAs('/private/tmp/ejuice-check-backup.json');
await page.locator('#import-file').setInputFiles('/private/tmp/ejuice-check-backup.json');await page.getByRole('button',{name:'Bekræft'}).click();
await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await context.setOffline(true);await page.reload();await page.getByRole('heading',{name:'Mere',exact:true}).waitFor();await context.setOffline(false);
await page.setViewportSize({width:1200,height:900});await page.getByRole('link',{name:'Blandinger',exact:true}).click();await page.getByRole('button',{name:/Browser test/}).click();await page.screenshot({path:'/private/tmp/ejuice-desktop.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('Browser checks passed: edit, reload, undo/redo, snapshots, batch, mobile layout, backup roundtrip, offline.');await browser.close();
