import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.EJUICE_PLAYWRIGHT||'playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext();
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.setViewportSize({width:1024,height:900});await page.goto(process.env.EJUICE_URL||'http://127.0.0.1:8080');
await page.getByRole('link',{name:'Ingredienser'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
const columns=page.locator('.ingredient-column');assert.equal(await columns.count(),3);
assert.deepEqual(await columns.locator('h2').allTextContents(),['Baser','Aromaer','Tilsætningsstoffer']);
const widths=await columns.evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().width));assert.ok(widths[1]>widths[2]&&widths[2]>widths[0]);
await columns.nth(0).getByRole('button',{name:'+ Tilføj'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await columns.count(),0);assert.equal(await page.locator('[data-field="category"]').inputValue(),'base');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
await columns.nth(1).getByRole('button',{name:'+ Tilføj'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await page.locator('[data-field="category"]').inputValue(),'aroma');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
await columns.nth(2).getByRole('button',{name:'+ Tilføj'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await page.locator('[data-field="category"]').inputValue(),'additive');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
await columns.nth(0).locator('.ingredient-item').first().click();await page.getByRole('button',{name:'Fortsæt'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await columns.count(),0);await page.locator('[data-field="name"]').fill('Midlertidigt navn');await page.getByRole('button',{name:'Annuller'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();assert.ok((await columns.nth(0).innerText()).includes('Ny base'));
await columns.nth(0).locator('.ingredient-item').first().click();await page.getByRole('button',{name:'Fortsæt'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();await page.locator('[data-field="name"]').fill('Testbase');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();assert.ok((await columns.nth(0).innerText()).includes('Testbase'));
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const tops=await columns.evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().top));assert.ok(tops[0]<tops[1]&&tops[1]<tops[2]);
await page.getByRole('link',{name:'Blandinger'}).click();await page.getByRole('heading',{name:'Blandinger'}).waitFor();await page.getByRole('button',{name:'+ Ny blanding'}).click();
assert.equal(await page.locator('[data-field="target"]').count(),1);assert.equal(await page.locator('[data-field="nicotineBaseId"]').count(),1);assert.ok((await page.locator('[data-field="fillBaseId"]').locator('xpath=..').innerText()).includes('Fortyndingsbase'));
await page.locator('[data-field="nicotineMode"]').selectOption('base');assert.equal(await page.locator('[data-field="target"]').count(),0);assert.equal(await page.locator('[data-field="nicotineBaseId"]').count(),0);assert.ok((await page.locator('[data-field="fillBaseId"]').locator('xpath=..').innerText()).includes('Nikotinbase'));assert.equal(await page.locator('[data-field="nicotineMode"] option:checked').innerText(),'Nikotin bestemt af basen');
await page.getByRole('button',{name:'+ Tilføj ingrediens'}).click();assert.deepEqual(await page.locator('[data-row="mode"] option').allTextContents(),['Vægt %','Volumen %','Gram pr. batch','Dråber pr. batch']);
await page.getByRole('link',{name:'Mere'}).click();await page.getByRole('heading',{name:'Mere'}).waitFor();assert.equal(await page.locator('[data-field="set-dropsPgVg"]').inputValue(),'68');assert.equal(await page.locator('[data-field="set-dropsEthanol"]').inputValue(),'125');
assert.deepEqual(errors,[]);console.log('Responsive and nicotine field checks passed');await browser.close();
