import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.EJUICE_PLAYWRIGHT||'playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext();
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.setViewportSize({width:1024,height:900});await page.goto(process.env.EJUICE_URL||'http://127.0.0.1:8080');
await page.getByRole('link',{name:'Ingredienser'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
const columns=page.locator('.ingredient-column');assert.equal(await columns.count(),3);
assert.deepEqual(await columns.locator('h2').allTextContents(),['Baser','Aromaer','Tilsætningsstoffer']);
const widths=await columns.evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().width));assert.ok(widths[1]>widths[2]&&widths[2]>widths[0]);
await columns.nth(0).getByRole('button',{name:'+ Tilføj'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await columns.count(),0);assert.equal(await page.locator('[data-field="category"]').inputValue(),'base');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
await columns.nth(1).getByRole('button',{name:'+ Tilføj'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await page.locator('[data-field="category"]').inputValue(),'aroma');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
await columns.nth(2).getByRole('button',{name:'+ Tilføj'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await page.locator('[data-field="category"]').inputValue(),'additive');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
await columns.nth(1).getByRole('button',{name:'+ Tilføj'}).click();await page.locator('[data-field="name"]').fill('Ekstra aroma');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();
await columns.nth(0).locator('.ingredient-item').first().click();await page.getByRole('button',{name:'Fortsæt'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();assert.equal(await columns.count(),0);await page.locator('[data-field="name"]').fill('Midlertidigt navn');await page.getByRole('button',{name:'Annuller'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();assert.ok((await columns.nth(0).innerText()).includes('Ny base'));
await columns.nth(0).locator('.ingredient-item').first().click();await page.getByRole('button',{name:'Fortsæt'}).click();await page.getByRole('button',{name:'Gem og lås'}).waitFor();await page.locator('[data-field="name"]').fill('Testbase');await page.locator('[data-field="strength"]').fill('3');await page.getByRole('button',{name:'Gem og lås'}).click();await page.getByRole('heading',{name:'Ingredienser'}).waitFor();assert.ok((await columns.nth(0).innerText()).includes('Testbase'));
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const tops=await columns.evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().top));assert.ok(tops[0]<tops[1]&&tops[1]<tops[2]);
await page.getByRole('link',{name:'Blandinger'}).click();await page.getByRole('heading',{name:'Blandinger'}).waitFor();await page.getByRole('button',{name:'+ Ny blanding'}).click();
assert.equal(await page.locator('[data-field="target"]').count(),1);assert.equal(await page.locator('[data-field="nicotineBaseId"]').count(),1);assert.ok((await page.locator('[data-field="fillBaseId"]').locator('xpath=..').innerText()).includes('Fortyndingsbase'));
await page.locator('[data-field="nicotineMode"]').selectOption('base');assert.equal(await page.locator('[data-field="target"]').count(),0);assert.equal(await page.locator('[data-field="nicotineBaseId"]').count(),0);assert.ok((await page.locator('[data-field="fillBaseId"]').locator('xpath=..').innerText()).includes('Nikotinbase'));assert.equal(await page.locator('[data-field="nicotineMode"] option:checked').innerText(),'Nikotin bestemt af basen');
await page.locator('[data-field="fillBaseId"]').selectOption({index:1});
await page.getByRole('button',{name:'+ Tilføj ingrediens'}).click();
assert.deepEqual(await page.locator('[data-row="mode"] option').allTextContents(),['vægt%','vol%','Gram pr. batch','Dråber pr. batch']);
const calculatedFirstRow=()=>page.locator('#result .data-table tbody tr').first().locator('th,td').allTextContents();
await page.locator('[data-row="mode"]').selectOption('volume');
await page.locator('[data-row="amount"]').fill('5');
await page.locator('[data-row="amount"]').press('Tab');
assert.equal(await page.locator('[data-row="amount"]').inputValue(),'5.00');
const volumeResult=await calculatedFirstRow();assert.equal(volumeResult.length,6);
await page.locator('[data-row="mode"]').selectOption('weight');
assert.match(await page.locator('[data-row="amount"]').inputValue(),/^\d+\.\d{2}$/);
assert.equal(await page.locator('[data-row="amount"]').getAttribute('step'),'.01');
assert.deepEqual(await calculatedFirstRow(),volumeResult);
await page.locator('[data-row="mode"]').selectOption('grams');
assert.match(await page.locator('[data-row="amount"]').inputValue(),/^\d+\.\d{2}$/);
assert.deepEqual(await calculatedFirstRow(),volumeResult);
await page.locator('[data-row="mode"]').selectOption('volume');
assert.equal(await page.locator('[data-row="amount"]').inputValue(),'5.00');
await page.locator('[data-row="mode"]').selectOption('drops');
assert.match(await page.locator('[data-row="amount"]').inputValue(),/^\d+$/);
assert.equal(await page.locator('[data-row="amount"]').getAttribute('step'),'1');
const dropResult=await calculatedFirstRow();
await page.locator('[data-row="mode"]').selectOption('grams');
assert.match(await page.locator('[data-row="amount"]').inputValue(),/^\d+\.\d{2}$/);
assert.deepEqual(await calculatedFirstRow(),dropResult);
await page.locator('[data-row="mode"]').selectOption('volume');
assert.equal(await page.locator('[data-row="amount"]').inputValue(),'5.00');
await page.getByRole('button',{name:'Gem og lås'}).click();
assert.match(await page.locator('.blend-row .blend-meta').first().innerText(),/Oprettet:/);assert.equal(await page.locator('.blend-row [data-a="rating"]').count(),0);assert.equal(await page.locator('.blend-row .blend-rating-display').first().innerText(),'0/10');
await page.locator('.blend-row .row-title').first().click();await page.getByRole('button',{name:'Fortsæt'}).click();await page.locator('[data-a="editrating"][data-rating="7"]').click();assert.match(await page.locator('.editor-ranking').innerText(),/7\/10/);await page.getByRole('button',{name:'Annuller'}).click();assert.equal(await page.locator('.blend-row .blend-rating-display').first().innerText(),'0/10');
await page.locator('.blend-row .row-title').first().click();await page.getByRole('button',{name:'Fortsæt'}).click();await page.locator('[data-a="editrating"][data-rating="7"]').click();await page.getByRole('button',{name:'Gem og lås'}).click();assert.equal(await page.locator('.blend-row .rating-score').first().innerText(),'7/10');assert.equal(await page.locator('.blend-row .rating-stars').first().innerText(),'★★★★★★★');assert.equal((await page.locator('.blend-row .blend-rating-display').first().innerText()).includes('☆'),false);
await page.getByRole('button',{name:'Sortér efter: Oprettelsesdato'}).click();assert.equal(await page.getByRole('button',{name:'Sortér efter: Navn'}).count(),1);
await page.reload();await page.getByRole('heading',{name:'Blandinger'}).waitFor();assert.equal(await page.getByRole('button',{name:'Sortér efter: Navn'}).count(),1);assert.equal(await page.locator('.blend-row .rating-stars').first().innerText(),'★★★★★★★');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.setViewportSize({width:1024,height:900});const metaCenters=await page.locator('.blend-row .blend-meta').first().evaluate(el=>[...el.children].map(child=>{const box=child.getBoundingClientRect();return Math.round(box.top+box.height/2)}));assert.ok(Math.max(...metaCenters)-Math.min(...metaCenters)<4);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.getByRole('link',{name:'Udvikling'}).click();await page.getByRole('heading',{name:'Udvikling'}).waitFor();await page.getByRole('button',{name:'+ Ny udviklingssession'}).click();assert.equal(await page.locator('[data-start-panel="weighed"]').isHidden(),true);await page.getByLabel('Startmængde · ml').fill('');await page.getByRole('button',{name:'Start session'}).click();await page.getByRole('alert').waitFor();await page.locator('#dialog').getByRole('button',{name:'Annuller'}).click();await page.getByRole('link',{name:'Blandinger'}).click();await page.getByRole('heading',{name:'Blandinger'}).waitFor();assert.equal(await page.getByRole('alert').isHidden(),true);
await page.getByRole('link',{name:'Udvikling'}).click();await page.getByRole('button',{name:'+ Ny udviklingssession'}).click();await page.getByLabel('Startmængde · ml').fill('');await page.getByRole('button',{name:'Start session'}).click();await page.locator('#dialog').getByRole('button',{name:'Annuller'}).click();await page.getByRole('alert').getByRole('button',{name:'Luk fejlmeddelelse'}).click();assert.equal(await page.getByRole('alert').isHidden(),true);
await page.getByRole('button',{name:'+ Ny udviklingssession'}).click();await page.getByLabel('Beholderens tomvægt · g').fill('4');await page.getByRole('button',{name:'Start session'}).click();await page.getByRole('button',{name:'+ Tilføj ingrediens'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
const compositionTable=page.locator('.development-grid .data-table');
assert.deepEqual(await compositionTable.locator('thead th').allTextContents(),['Ingrediens','Gram','ml','vol%','vægt%','Dråber ca.']);
const volumePercents=await compositionTable.locator('tbody tr').evaluateAll(rows=>rows.map(row=>Number(row.children[3].textContent.replace(',','.'))));
assert.ok(Math.abs(volumePercents.reduce((sum,value)=>sum+value,0)-100)<0.05);
await page.locator('[data-percent-mode]').selectOption('weight');assert.deepEqual(await compositionTable.locator('thead th').allTextContents(),['Ingrediens','Gram','ml','vægt%','vol%','Dråber ca.']);const firstWeight=await compositionTable.locator('tbody tr').first().locator('.preferred-percent').innerText();await page.getByRole('button',{name:'Beregn mål'}).click();assert.equal(await page.locator('[data-target-current]').first().locator('[data-target-percent]').inputValue(),String(Number(firstWeight.replace(',','.'))));await page.getByRole('button',{name:'Luk beregningshjælp'}).click();await page.locator('[data-percent-mode]').selectOption('volume');
await page.setViewportSize({width:1024,height:900});
const developmentWidths=await page.locator('.development-grid > section').evaluateAll(sections=>sections.map(section=>section.getBoundingClientRect().width));
assert.equal(developmentWidths.length,2);assert.ok(Math.abs(developmentWidths[0]-developmentWidths[1])<1);
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.equal(await page.locator('[data-dev-capacity]').inputValue(),'10');await page.getByRole('button',{name:'Beregn mål'}).click();assert.equal(await page.locator('[data-target-current]').first().locator('[data-target-percent]').inputValue(),'5');await page.locator('[data-target-current]').first().locator('[data-target-percent]').fill('3.5');await page.locator('#target-preview').getByText('Flasken er for lille.',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('[data-target-current]').count(),2);const desired=page.locator('[data-target-volume]');await desired.fill('12');assert.ok((await page.locator('#target-preview').innerText()).includes('større end de beregnede'));await desired.fill('20');assert.ok((await page.locator('#target-preview').innerText()).includes('20,00 ml'));assert.ok((await page.locator('#target-preview .target-additions').innerText()).includes('Ny ingrediens'));await desired.fill('');await page.locator('[data-target-add]').click();await page.locator('.target-new').first().locator('[data-target-ingredient]').selectOption({label:'Nyt tilsætningsstof'});await page.locator('.target-new').first().locator('[data-target-percent]').fill('2');await page.locator('[data-target-add]').click();await page.locator('.target-new').nth(1).locator('[data-target-ingredient]').selectOption({label:'Ekstra aroma'});await page.locator('.target-new').nth(1).locator('[data-target-percent]').fill('1');assert.ok((await page.locator('#target-preview').innerText()).includes('Nyt tilsætningsstof'));assert.ok((await page.locator('#target-preview').innerText()).includes('Ekstra aroma'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'Luk beregningshjælp'}).click();assert.equal(await page.locator('.timeline-item').count(),1);
await page.locator('[data-dev-capacity]').fill('20');await page.locator('[data-dev-capacity]').blur();await page.getByRole('button',{name:'Beregn mål'}).click();assert.ok((await page.locator('#target-preview').innerText()).includes('Ændr mindst ét procentmål'));
await page.locator('[data-target-volume]').fill('15');assert.ok((await page.locator('#target-preview').innerText()).includes('15,00 ml'));await page.getByRole('button',{name:'Overfør til registreringer'}).click();assert.equal(await page.locator('[data-transfer-ingredient]').count(),1);await page.getByRole('button',{name:'Tilbage til mål'}).click();await page.locator('[data-target-volume]').fill('');
await page.locator('[data-target-add]').click();await page.locator('.target-new [data-target-ingredient]').selectOption({label:'Nyt tilsætningsstof'});await page.locator('.target-new [data-target-percent]').fill('2');await page.getByRole('button',{name:'Overfør til registreringer'}).click();assert.equal(await page.locator('#target-form').isHidden(),true);assert.equal(await page.locator('.timeline-item').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByLabel('Faktisk mængde for Nyt tilsætningsstof i ml').fill('20');assert.equal(await page.getByRole('button',{name:'Jeg har tilsat · registrér'}).isDisabled(),true);await page.getByLabel('Faktisk mængde for Nyt tilsætningsstof i ml').fill('0.2');assert.ok((await page.locator('#transfer-preview').innerText()).includes('0,200 ml'));await page.getByRole('button',{name:'Tilbage til mål'}).click();assert.equal(await page.locator('.timeline-item').count(),1);await page.getByRole('button',{name:'Overfør til registreringer'}).click();await page.getByLabel('Faktisk mængde for Nyt tilsætningsstof i ml').fill('0.2');await page.getByRole('button',{name:'Jeg har tilsat · registrér'}).click();await page.locator('.timeline-item').nth(2).waitFor();assert.ok((await page.locator('.timeline').innerText()).includes('Overført fra målberegner'));
await page.getByRole('button',{name:'+ Tilføj ingrediens'}).click();await page.locator('select[name="ingredientId"]').selectOption({label:'Ny ingrediens'});await page.locator('[name="amount"]').fill('0.1');await page.getByRole('button',{name:'Registrér tilsætning'}).click();await page.locator('.timeline-item').nth(3).waitFor();assert.ok((await page.locator('.timeline').innerText()).includes('Ny ingrediens tilsat'));
await page.getByRole('button',{name:'Prøve udtaget'}).click();await page.getByLabel('Ny totalvægt · g').fill('14');await page.getByRole('button',{name:'Registrér prøve'}).click();await page.locator('.timeline-item').nth(4).waitFor();assert.ok((await page.locator('.timeline').innerText()).includes('Prøve udtaget'));
await page.getByRole('button',{name:'Opret ny blanding fra resultat'}).click();await page.getByLabel('Navn').fill('Test udvikling');await page.getByRole('button',{name:'Opret blanding'}).click();await page.getByRole('heading',{name:'Blandinger'}).waitFor();assert.ok((await page.locator('.list').innerText()).includes('Test udvikling'));
await page.locator('.row-title').filter({hasText:'Test udvikling'}).click();await page.getByRole('button',{name:'Fortsæt'}).click();await page.getByRole('button',{name:'Slet opskrift'}).waitFor();page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Slet opskrift'}).click();assert.equal(await page.getByRole('button',{name:'Slet opskrift'}).isVisible(),true);page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Slet opskrift'}).click();await page.getByRole('heading',{name:'Blandinger'}).waitFor();assert.equal((await page.locator('.list').innerText()).includes('Test udvikling'),false);
await page.getByRole('link',{name:'Mere'}).click();await page.getByRole('heading',{name:'Mere'}).waitFor();assert.equal(await page.locator('[data-field="set-dropsPgVg"]').inputValue(),'68');assert.equal(await page.locator('[data-field="set-dropsEthanol"]').inputValue(),'125');
assert.equal(await page.locator('[data-field="set-scaleResolution"]').inputValue(),'0.1');
assert.equal(await page.locator('[data-percent-mode]').inputValue(),'volume');await page.locator('[data-percent-mode]').selectOption('weight');await page.reload();await page.getByRole('link',{name:'Mere'}).click();assert.equal(await page.locator('[data-percent-mode]').inputValue(),'weight');await page.locator('[data-percent-mode]').selectOption('volume');
// Locked edits and fresh drafts must retain their cancellation semantics after a reload.
await page.getByRole('link',{name:'Ingredienser'}).click();
await columns.nth(0).locator('.ingredient-item').filter({hasText:'Testbase'}).click();
await page.locator('#dialog').getByRole('button',{name:'Fortsæt'}).click();
await page.locator('[data-field="name"]').fill('Annulleret basenavn');
await page.getByRole('button',{name:'Annuller'}).click();
await page.reload();
assert.ok((await columns.nth(0).innerText()).includes('Testbase'));
assert.equal((await columns.nth(0).innerText()).includes('Annulleret basenavn'),false);
const aromaCount=await columns.nth(1).locator('.ingredient-item').count();
await columns.nth(1).getByRole('button',{name:'+ Tilføj'}).click();
await page.locator('[data-field="name"]').fill('Annulleret aromakladde');
await page.getByRole('button',{name:'Annuller'}).click();
await page.locator('#save-status').filter({hasText:'Gemt lokalt'}).waitFor();
await page.reload();
assert.equal(await columns.nth(1).locator('.ingredient-item').count(),aromaCount);
assert.equal((await columns.nth(1).innerText()).includes('Annulleret aromakladde'),false);
await columns.nth(1).locator('.ingredient-item').filter({hasText:'Ekstra aroma'}).click();
await page.locator('#dialog').getByRole('button',{name:'Fortsæt'}).click();
await page.getByRole('button',{name:'Duplikér'}).click();
assert.equal(await page.locator('[data-field="name"]').inputValue(),'Ekstra aroma kopi');
await page.getByRole('button',{name:'Annuller'}).click();
await page.locator('#save-status').filter({hasText:'Gemt lokalt'}).waitFor();
await page.reload();
assert.equal(await columns.nth(1).locator('.ingredient-item').count(),aromaCount);

await page.getByRole('link',{name:'Blandinger'}).click();
const sourceName=await page.locator('.blend-row .row-title strong').first().innerText();
const recipeCount=await page.locator('.blend-row').count();
await page.locator('.blend-row .row-title').first().click();
await page.locator('#dialog').getByRole('button',{name:'Fortsæt'}).click();
const sourceBatch=await page.locator('[data-field="batch"]').inputValue();
await page.locator('[data-field="name"]').fill('Annulleret låst opskrift');
await page.getByRole('button',{name:'Annuller'}).click();
await page.reload();
assert.ok((await page.locator('.blend-row .row-title strong').allTextContents()).includes(sourceName));
assert.equal((await page.locator('.list').innerText()).includes('Annulleret låst opskrift'),false);
await page.getByRole('button',{name:'+ Ny blanding'}).click();
await page.locator('[data-field="name"]').fill('Annulleret ny blanding');
await page.getByRole('button',{name:'Annuller'}).click();
await page.locator('#save-status').filter({hasText:'Gemt lokalt'}).waitFor();
await page.reload();
assert.equal(await page.locator('.blend-row').count(),recipeCount);
assert.equal((await page.locator('.list').innerText()).includes('Annulleret ny blanding'),false);
const sourceRow=page.locator('.blend-row').filter({has:page.locator('.row-title').filter({hasText:sourceName})}).first();
await sourceRow.locator('[data-a="duprecipe"]').click();
assert.equal(await page.locator('[data-field="name"]').inputValue(),sourceName+' kopi');
assert.equal(await page.locator('[data-field="batch"]').inputValue(),sourceBatch);
await page.locator('[data-field="name"]').fill('Browserkopi');
await page.locator('[data-field="batch"]').fill('42');
await page.getByRole('button',{name:'Gem og lås'}).click();
await page.locator('#save-status').filter({hasText:'Gemt lokalt'}).waitFor();
await page.reload();
assert.ok((await page.locator('.blend-row .row-title strong').allTextContents()).includes('Browserkopi'));
await page.locator('.blend-row .row-title').filter({hasText:sourceName}).first().click();
await page.locator('#dialog').getByRole('button',{name:'Fortsæt'}).click();
assert.equal(await page.locator('[data-field="batch"]').inputValue(),sourceBatch);
await page.getByRole('button',{name:'Annuller'}).click();
await page.setViewportSize({width:320,height:700});
await page.locator('.blend-row .row-title').first().click();
await page.locator('#dialog').getByRole('button',{name:'Fortsæt'}).click();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.getByRole('button',{name:'Annuller'}).click();

// Intercept print so the generated sheet can be checked without opening a native print dialog.
await page.evaluate(()=>{window.__printCalls=0;window.print=()=>{window.__printCalls++}});
await page.locator('.blend-row').first().locator('[data-a="batch"]').click();
await page.locator('#dialog').getByRole('button',{name:'Udskriv batch-seddel/PDF'}).click();
assert.equal(await page.evaluate(()=>window.__printCalls),1);
assert.match(await page.locator('.print-sheet h1').innerText(),/batch-seddel/);
assert.ok(await page.locator('.print-sheet .batch-checklist li').count()>0);
assert.deepEqual(await page.locator('.print-sheet .data-table thead th').allTextContents(),['Ingrediens','Gram','ml','vol%','vægt%','Dråber ca.']);
await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));
assert.equal(await page.locator('.print-sheet').count(),0);
await page.getByRole('link',{name:'Mere'}).click();
await page.getByRole('button',{name:'Udskriv bibliotek/PDF'}).click();
assert.equal(await page.evaluate(()=>window.__printCalls),2);
assert.equal(await page.locator('.print-sheet .print-recipe').count(),recipeCount+1);
await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));

// A rejected import must leave the library untouched; an accepted import must be reversible.
await page.locator('#save-status').filter({hasText:'Gemt lokalt'}).waitFor();
const readSavedLibrary=()=>page.evaluate(()=>new Promise((resolve,reject)=>{
 const open=indexedDB.open('ejuice-lab-v3',1);
 open.onerror=()=>reject(open.error);
 open.onsuccess=()=>{
  const request=open.result.transaction('library').objectStore('library').get('current');
  request.onsuccess=()=>resolve(request.result);
  request.onerror=()=>reject(request.error);
 };
}));
const savedLibrary=await readSavedLibrary();
const waitForSavedRecipeName=name=>page.waitForFunction(async expected=>{
 const current=await new Promise((resolve,reject)=>{
  const open=indexedDB.open('ejuice-lab-v3',1);
  open.onerror=()=>reject(open.error);
  open.onsuccess=()=>{
   const request=open.result.transaction('library').objectStore('library').get('current');
   request.onsuccess=()=>resolve(request.result);
   request.onerror=()=>reject(request.error);
  };
 });
 return current?.recipes?.[0]?.name===expected;
},name);
const importedLibrary=structuredClone(savedLibrary);
importedLibrary.recipes[0].name='Importeret browseropskrift';
const importFile={name:'browser-import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(importedLibrary))};
const rejectedDialog=new Promise(resolve=>page.once('dialog',async dialog=>{const message=dialog.message();await dialog.dismiss();resolve(message)}));
await page.locator('#import-file').setInputFiles(importFile);
assert.match(await rejectedDialog,/browser-import\.json.*erstatter hele dit nuværende bibliotek/);
await page.waitForFunction(()=>document.querySelector('#import-file').value==='');
await page.reload();
await page.getByRole('link',{name:'Blandinger'}).click();
assert.equal((await page.locator('.list').innerText()).includes('Importeret browseropskrift'),false);
assert.equal(await page.locator('.blend-row').count(),recipeCount+1);
await page.getByRole('link',{name:'Mere'}).click();
const acceptedDialog=new Promise(resolve=>page.once('dialog',async dialog=>{const message=dialog.message();await dialog.accept();resolve(message)}));
await page.locator('#import-file').setInputFiles(importFile);
assert.match(await acceptedDialog,/browser-import\.json.*erstatter hele dit nuværende bibliotek/);
await waitForSavedRecipeName('Importeret browseropskrift');
await page.reload();
await page.getByRole('link',{name:'Blandinger'}).click();
assert.ok((await page.locator('.list').innerText()).includes('Importeret browseropskrift'));
await page.getByRole('link',{name:'Mere'}).click();
const restoredDialog=new Promise(resolve=>page.once('dialog',async dialog=>{await dialog.accept();resolve()}));
await page.getByRole('button',{name:'Gendan før sidste import'}).click();
await restoredDialog;
await waitForSavedRecipeName(savedLibrary.recipes[0].name);
await page.reload();
await page.getByRole('link',{name:'Blandinger'}).click();
assert.equal((await page.locator('.list').innerText()).includes('Importeret browseropskrift'),false);
assert.ok((await page.locator('.blend-row .row-title strong').allTextContents()).includes(sourceName));
assert.deepEqual(errors,[]);console.log('Browser QA passed: responsive layout, recipes, development, cancel/duplicate, import/restore, and print sheets');await browser.close();
