import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyDB,ingredient,recipe,solve,capture,merge,migrateV1,validate,referenced} from './model.js';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function fixture(){const db=emptyDB();const base={...ingredient(),category:'base',name:'50/50',pg:50,vg:50,density:1.1485};const aroma={...ingredient(),name:'Aroma'};const nic={...ingredient(),name:'Nic',category:'nicotine',strength:52};db.ingredients.push(base,aroma,nic);const r=recipe(base);db.recipes.push(r);return {db,base,aroma,nic,r};}
test('weight percentages, volume, nicotine and mass balance at multiple sizes',()=>{const {db,r,aroma,nic}=fixture();r.draft.rows=[{ingredientId:aroma.id,mode:'weight',amount:10},{ingredientId:nic.id,mode:'nic',amount:1}];for(const size of [10,37.5,100,200]){const x=solve(r.draft,db.ingredients,size);close(x.items.reduce((s,i)=>s+i.ml,0),size);close(x.items[0].grams/x.total,.1);close(x.strength,3);close(x.pg+x.vg+x.ethanol,100);}});
test('g/ml and multiple nicotine bases scale',()=>{const {db,r,aroma,nic}=fixture();const n2={...nic,id:'second',strength:20};db.ingredients.push(n2);r.draft.rows=[{ingredientId:aroma.id,mode:'gml',amount:.01},{ingredientId:nic.id,mode:'nic',amount:1},{ingredientId:n2.id,mode:'nic',amount:3}];const x=solve(r.draft,db.ingredients,50);close(x.items[0].grams,.5);close(x.strength,3);close(x.items[2].ml*20/(x.items[1].ml*52),3);});
test('nicotine in fill-up premix is counted',()=>{const {db,r,base,nic,aroma}=fixture();base.strength=3;r.draft.target=6;r.draft.rows=[{ingredientId:aroma.id,mode:'weight',amount:10},{ingredientId:nic.id,mode:'nic',amount:1}];close(solve(r.draft,db.ingredients).strength,6);});
test('impossible recipes and invalid carrier are rejected',()=>{const {db,r,aroma}=fixture();r.draft.rows=[{ingredientId:aroma.id,mode:'gml',amount:4}];assert.throws(()=>solve(r.draft,db.ingredients));r.draft.rows=[];db.ingredients[0].pg=80;assert.throws(()=>solve(r.draft,db.ingredients));});
test('historical ingredient values are independent',()=>{const {db,r,aroma}=fixture();r.draft.rows=[{ingredientId:aroma.id,mode:'weight',amount:10}];const s=capture(r.draft,db.ingredients),before=solve(s.draft,s.ingredients);aroma.density=2;close(solve(s.draft,s.ingredients).total,before.total);assert.notEqual(solve(r.draft,db.ingredients).total,before.total);});
test('merge retains conflicts and maps historical references',()=>{const {db,r,aroma}=fixture();r.draft.rows=[{ingredientId:aroma.id,mode:'weight',amount:10}];r.versions.push(capture(r.draft,db.ingredients));const incoming=structuredClone(db);incoming.ingredients[1].name='Changed';incoming.recipes[0].name='Changed recipe';const merged=merge(db,incoming);validate(merged);assert.equal(merged.recipes.length,2);const imported=merged.recipes[1],key=imported.draft.rows[0].ingredientId;assert.notEqual(key,aroma.id);assert.equal(imported.versions[0].draft.rows[0].ingredientId,key);assert.ok(referenced(merged,key));assert.equal(merge(db,db).recipes.length,1);});
test('v1 library migration preserves target and weight fraction',()=>{const db=migrateV1({format:'ejuice-mixer-library',version:1,recipes:[{name:'Old',state:{totalMl:100,targetNic:3,pgRatio:50,nics:[{name:'Nic',strength:52,pg:100,share:100}],aromas:[{name:'A',percent:10,pg:100,density:1.036,solvent:'pg'}]}}]});const x=solve(db.recipes[0].draft,db.ingredients);close(x.strength,3);close(x.items[1].grams/x.total,.1);validate(db);});
test('unrecognized backups rejected without changes',()=>{assert.throws(()=>validate({version:99}));assert.throws(()=>migrateV1({recipes:[]}));});
test('purchase details are stored and do not affect calculation validation',()=>{const {db,aroma}=fixture();aroma.purchasedFrom='VapeShop';aroma.purchaseUrl='https://example.com/aroma';aroma.purchasePrice=79.95;aroma.purchaseAmount=30;validate(db);assert.equal(aroma.purchasePrice/aroma.purchaseAmount,2.665);aroma.purchaseUrl='www.example.com/aroma';validate(db);aroma.purchasePrice=-1;assert.throws(()=>validate(db));});
test('fill-up base mode derives diluted nicotine strength without a target',()=>{const {db,r,base,aroma,nic}=fixture();base.strength=3;r.draft.nicotineMode='base';r.draft.rows=[{ingredientId:aroma.id,mode:'weight',amount:10}];const x=solve(r.draft,db.ingredients);assert.equal(x.warnings.length,0);assert.ok(x.strength>2.5&&x.strength<3);r.draft.rows.push({ingredientId:nic.id,mode:'nic',amount:1});assert.throws(()=>solve(r.draft,db.ingredients),/Nikotinandelsdosering/);});
