import test from 'node:test';import assert from 'node:assert/strict';import {emptyDB,ingredient,recipe,solve,referenced,dropsPerMl,normalize} from './model.js';
function base(db,name,category,strength=0){const x=ingredient(db.settings);Object.assign(x,{name,category,strength,pg:50,vg:50,density:1.1485});db.ingredients.push(x);return x}
test('beregner én nikotinbase og fyld-op-base',()=>{const db=emptyDB(),fill=base(db,'Neutral','base'),nic=base(db,'52 mg','nicotine',52),a=base(db,'Aroma','aroma');a.pg=100;a.vg=0;a.density=1.036;const r=recipe();r.draft.fillBaseId=fill.id;r.draft.nicotineBaseId=nic.id;r.draft.target=3;r.draft.rows=[{ingredientId:a.id,mode:'weight',amount:10}];const x=solve(r.draft,db.ingredients);assert.ok(Math.abs(x.strength-3)<.01);assert.equal(x.batch,100)});
test('beregner nikotin bestemt af basen efter fortynding',()=>{const db=emptyDB(),nic=base(db,'3 mg base','nicotine',3),a=base(db,'Aroma','aroma');a.pg=100;a.vg=0;a.density=1.036;const r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=nic.id;r.draft.rows=[{ingredientId:a.id,mode:'volume',amount:10}];const x=solve(r.draft,db.ingredients,100,db.settings);assert.ok(Math.abs(x.strength-2.7)<.01);assert.equal(x.items[0].ml,10)});
test('gram pr batch skalerer med batchstørrelsen',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma','aroma');const r=recipe();r.draft.nicotineMode='base';r.draft.batch=10;r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'grams',amount:.1}];const x=solve(r.draft,db.ingredients,20,db.settings);assert.ok(Math.abs(x.items[0].grams-.2)<1e-9)});
test('dråber pr batch bruger PG/VG og ethanol-konstanter og skalerer',()=>{const db=emptyDB(),fill=base(db,'Base','base'),pg=base(db,'PG aroma','aroma'),eth=base(db,'Ethanol aroma','aroma');pg.pg=100;pg.vg=0;pg.density=db.settings.pg;eth.pg=0;eth.vg=0;eth.ethanol=100;eth.density=db.settings.ethanol;const r=recipe();r.draft.nicotineMode='base';r.draft.batch=10;r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:pg.id,mode:'drops',amount:68},{ingredientId:eth.id,mode:'drops',amount:125}];const x=solve(r.draft,db.ingredients,20,db.settings);assert.ok(Math.abs(x.items[0].ml-2)<1e-9);assert.ok(Math.abs(x.items[1].ml-2)<1e-9);assert.equal(dropsPerMl(pg,db.settings),68);assert.equal(dropsPerMl(eth,db.settings),125)});
test('individuel dråbeværdi tilsidesætter automatisk beregning',()=>{const db=emptyDB(),a=base(db,'Aroma','aroma');a.dropsOverride=80;assert.equal(dropsPerMl(a,db.settings),80)});
test('gamle gml-rækker konverteres kompatibelt til gram pr batch',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma','aroma'),r=recipe();r.draft.batch=10;r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'gml',amount:.01}];db.recipes.push(r);normalize(db);assert.equal(r.draft.rows[0].mode,'grams');assert.equal(r.draft.rows[0].amount,.1)});
test('reference finder kun aktive opskrifter',()=>{const db=emptyDB(),i=base(db,'Base','base'),r=recipe();r.draft.fillBaseId=i.id;db.recipes.push(r);assert.equal(referenced(db,i.id)[0].id,r.id)});
