import test from 'node:test';import assert from 'node:assert/strict';import {emptyDB,ingredient,recipe,solve,referenced,dropsPerMl,normalize} from './model.js';
import {createDevelopmentSession,developmentState,appendDevelopmentEvent,replaceDevelopmentEvent,developmentToRecipe,planDevelopmentTargets} from './development.js';
function base(db,name,category,strength=0){const x=ingredient(db.settings);Object.assign(x,{name,category,strength,pg:50,vg:50,density:1.1485});db.ingredients.push(x);return x}
test('beregner én nikotinbase og fyld-op-base',()=>{const db=emptyDB(),fill=base(db,'Neutral','base'),nic=base(db,'52 mg','nicotine',52),a=base(db,'Aroma','aroma');a.pg=100;a.vg=0;a.density=1.036;const r=recipe();r.draft.fillBaseId=fill.id;r.draft.nicotineBaseId=nic.id;r.draft.target=3;r.draft.rows=[{ingredientId:a.id,mode:'weight',amount:10}];const x=solve(r.draft,db.ingredients);assert.ok(Math.abs(x.strength-3)<.01);assert.equal(x.batch,100)});
test('beregner nikotin bestemt af basen efter fortynding',()=>{const db=emptyDB(),nic=base(db,'3 mg base','nicotine',3),a=base(db,'Aroma','aroma');a.pg=100;a.vg=0;a.density=1.036;const r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=nic.id;r.draft.rows=[{ingredientId:a.id,mode:'volume',amount:10}];const x=solve(r.draft,db.ingredients,100,db.settings);assert.ok(Math.abs(x.strength-2.7)<.01);assert.equal(x.items[0].ml,10)});
test('gram pr batch skalerer med batchstørrelsen',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma','aroma');const r=recipe();r.draft.nicotineMode='base';r.draft.batch=10;r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'grams',amount:.1}];const x=solve(r.draft,db.ingredients,20,db.settings);assert.ok(Math.abs(x.items[0].grams-.2)<1e-9)});
test('dråber pr batch bruger PG/VG og ethanol-konstanter og skalerer',()=>{const db=emptyDB(),fill=base(db,'Base','base'),pg=base(db,'PG aroma','aroma'),eth=base(db,'Ethanol aroma','aroma');pg.pg=100;pg.vg=0;pg.density=db.settings.pg;eth.pg=0;eth.vg=0;eth.ethanol=100;eth.density=db.settings.ethanol;const r=recipe();r.draft.nicotineMode='base';r.draft.batch=10;r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:pg.id,mode:'drops',amount:68},{ingredientId:eth.id,mode:'drops',amount:125}];const x=solve(r.draft,db.ingredients,20,db.settings);assert.ok(Math.abs(x.items[0].ml-2)<1e-9);assert.ok(Math.abs(x.items[1].ml-2)<1e-9);assert.equal(dropsPerMl(pg,db.settings),68);assert.equal(dropsPerMl(eth,db.settings),125)});
test('individuel dråbeværdi tilsidesætter automatisk beregning',()=>{const db=emptyDB(),a=base(db,'Aroma','aroma');a.dropsOverride=80;assert.equal(dropsPerMl(a,db.settings),80)});
test('gamle gml-rækker konverteres kompatibelt til gram pr batch',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma','aroma'),r=recipe();r.draft.batch=10;r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'gml',amount:.01}];db.recipes.push(r);normalize(db);assert.equal(r.draft.rows[0].mode,'grams');assert.equal(r.draft.rows[0].amount,.1)});
test('reference finder kun aktive opskrifter',()=>{const db=emptyDB(),i=base(db,'Base','base'),r=recipe();r.draft.fillBaseId=i.id;db.recipes.push(r);assert.equal(referenced(db,i.id)[0].id,r.id)});
test('eksisterende ingredienser uden låsestatus bliver låst',()=>{const db=emptyDB(),i=ingredient(db.settings);delete i.locked;db.ingredients.push(i);normalize(db);assert.equal(i.locked,true)});
test('udviklingssession kan starte alene fra en kendt volumen',()=>{const db=emptyDB(),fill=base(db,'Base','base'),r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;const session=createDevelopmentSession(r,db.ingredients,db.settings,{name:'Volumen',startMode:'volume',startVolume:10,tare:4,startGross:''}),state=developmentState(session,db.settings);assert.equal(session.startMode,'volume');assert.ok(Math.abs(state.volume-10)<1e-9);assert.ok(session.startGross>4)});
test('udviklingssession kan starte alene fra en målt totalvægt',()=>{const db=emptyDB(),fill=base(db,'Base','base'),r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;const session=createDevelopmentSession(r,db.ingredients,db.settings,{name:'Vægt',startMode:'weighed',startVolume:'',tare:4,startGross:15}),state=developmentState(session,db.settings);assert.equal(session.startMode,'weighed');assert.equal(session.startGross,15);assert.ok(state.volume>0);assert.ok(Math.abs(state.mass-11)<1e-9)});
test('udviklingssession følger prøveudtagning og tilsætning som massebalance',()=>{const db=emptyDB(),fill=base(db,'3 mg base','nicotine',3),a=base(db,'Aroma','aroma');a.pg=100;a.vg=0;a.density=db.settings.pg;const r=recipe();r.name='Original';r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'volume',amount:10}];const initial=solve(r.draft,db.ingredients,10,db.settings),session=createDevelopmentSession(r,db.ingredients,db.settings,{name:'Forsøg',startVolume:10,tare:20,startGross:20+initial.total});const before=developmentState(session,db.settings);appendDevelopmentEvent(session,{type:'withdrawal',gross:20+before.mass/2},db.settings);appendDevelopmentEvent(session,{type:'addition',ingredientId:a.id,method:'amount',unit:'grams',amount:.1},db.settings);const after=developmentState(session,db.settings);assert.ok(Math.abs(after.mass-(before.mass/2+.1))<1e-9);assert.equal(after.steps.length,2);assert.ok(after.items.find(x=>x.id===a.id).grams>before.items.find(x=>x.id===a.id).grams/2)});
test('målt tilsætning og rettelse genberegner efterfølgende trin',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma','aroma'),r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;const initial=solve(r.draft,db.ingredients,10,db.settings),session=createDevelopmentSession(r,db.ingredients,db.settings,{name:'Forsøg',startVolume:10,tare:5,startGross:5+initial.total});const current=developmentState(session,db.settings),event=appendDevelopmentEvent(session,{type:'addition',ingredientId:a.id,method:'weighed',gross:5+current.mass+.2},db.settings);assert.ok(Math.abs(developmentState(session,db.settings).steps[0].deltaGrams-.2)<1e-9);replaceDevelopmentEvent(session,event.id,{gross:5+current.mass+.3},db.settings);assert.ok(Math.abs(developmentState(session,db.settings).steps[0].deltaGrams-.3)<1e-9)});
test('udviklingsresultat bliver en låst normaliseret opskrift',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma','aroma'),r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'volume',amount:5}];const initial=solve(r.draft,db.ingredients,10,db.settings),session=createDevelopmentSession(r,db.ingredients,db.settings,{name:'Ny opskrift',startVolume:10,tare:0,startGross:initial.total});appendDevelopmentEvent(session,{type:'addition',ingredientId:a.id,method:'amount',unit:'drops',amount:10},db.settings);const state=developmentState(session,db.settings),made=developmentToRecipe(session,db.settings,'Resultat'),mixed=solve(made.draft,db.ingredients,100,db.settings);assert.equal(made.locked,true);assert.equal(made.draft.batch,100);assert.equal(made.draft.rows[0].mode,'weight');assert.equal(made.name,'Resultat');assert.ok(made.draft.rows[0].amount>0);assert.ok(Math.abs(mixed.strength-state.strength)<1e-9);assert.ok(Math.abs(mixed.items.find(x=>x.id===a.id).grams/mixed.total-state.items.find(x=>x.id===a.id).grams/state.mass)<1e-9)});

test('målberegner fortynding og ny aroma i volumenprocent uden at ændre sessionen',()=>{const db=emptyDB(),fill=base(db,'3 mg base','nicotine',3),a=base(db,'Lakrids-mentol','aroma'),b=base(db,'Svejdehagl','aroma'),r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'volume',amount:10}];const session=createDevelopmentSession(r,db.ingredients,db.settings,{startMode:'volume',startVolume:10,tare:4});const plan=planDevelopmentTargets(session,db.settings,{primaryId:a.id,primaryPercent:7,secondaryId:b.id,secondaryPercent:3});assert.ok(Math.abs(plan.finalVolume-10/7*10)<1e-8);assert.ok(Math.abs(plan.additions.find(x=>x.ingredientId===b.id).ml-plan.finalVolume*.03)<1e-8);assert.ok(Math.abs(plan.additions.find(x=>x.ingredientId===fill.id).ml-(plan.finalVolume-10-plan.finalVolume*.03))<1e-8);assert.equal(plan.overCapacity,true);assert.equal(session.events.length,0)});
test('målberegner bruger tilbageværende prøve og redigerbar flaskekapacitet',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma','aroma'),r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'volume',amount:10}];const session=createDevelopmentSession(r,db.ingredients,db.settings,{startMode:'volume',startVolume:10,tare:4,capacity:10});const before=developmentState(session,db.settings);appendDevelopmentEvent(session,{type:'withdrawal',gross:4+before.mass*2/3},db.settings);const plan=planDevelopmentTargets(session,db.settings,{primaryId:a.id,primaryPercent:7});assert.ok(Math.abs(plan.finalVolume-(10*2/3)*10/7)<1e-8);assert.equal(plan.overCapacity,false);session.bottleCapacity=8;assert.equal(planDevelopmentTargets(session,db.settings,{primaryId:a.id,primaryPercent:7}).overCapacity,true)});
test('målberegner afviser mål der kræver at en ingrediens fjernes',()=>{const db=emptyDB(),fill=base(db,'Base','base'),a=base(db,'Aroma A','aroma'),b=base(db,'Aroma B','aroma'),r=recipe();r.draft.nicotineMode='base';r.draft.fillBaseId=fill.id;r.draft.rows=[{ingredientId:a.id,mode:'volume',amount:10},{ingredientId:b.id,mode:'volume',amount:20}];const session=createDevelopmentSession(r,db.ingredients,db.settings,{startMode:'volume',startVolume:10,tare:4});assert.throws(()=>planDevelopmentTargets(session,db.settings,{primaryId:a.id,primaryPercent:7,secondaryId:b.id,secondaryPercent:2}),/kan ikke fjernes/);assert.throws(()=>planDevelopmentTargets(session,db.settings,{primaryId:a.id,primaryPercent:12}),/lavere/)});
